{ domain: null,
  _events: {},
  _maxListeners: 10,
  socket: 
   { domain: null,
     _events: 
      { drain: [Function: ondrain],
        timeout: [Object],
        error: [Function],
        close: [Object] },
     _maxListeners: 10,
     _handle: 
      { writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 62894,
     _bytesDispatched: 80531,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _connections: 6,
        connections: [Getter/Setter],
        allowHalfOpen: true,
        _handle: [Object],
        httpAllowHalfOpen: false,
        _connectionKey: '4:0.0.0.0:3005' },
     _idleTimeout: 120000,
     _idleNext: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 25218,
        _bytesDispatched: 9977,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Sat Dec 01 2012 11:11:40 GMT+1000 (EST),
        parser: [Object],
        ondata: [Function],
        onend: [Function],
        _httpMessage: null,
        _paused: false },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Sat Dec 01 2012 11:11:42 GMT+1000 (EST),
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        app: [Object],
        _headers: [Object],
        _headerNames: [Object],
        req: [Circular],
        viewCallbacks: [],
        locals: [Object],
        end: [Function] },
     _paused: false,
     _peername: { address: '127.0.0.1', family: 'IPv4', port: 57235 } },
  connection: 
   { domain: null,
     _events: 
      { drain: [Function: ondrain],
        timeout: [Object],
        error: [Function],
        close: [Object] },
     _maxListeners: 10,
     _handle: 
      { writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 62894,
     _bytesDispatched: 80531,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _connections: 6,
        connections: [Getter/Setter],
        allowHalfOpen: true,
        _handle: [Object],
        httpAllowHalfOpen: false,
        _connectionKey: '4:0.0.0.0:3005' },
     _idleTimeout: 120000,
     _idleNext: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 25218,
        _bytesDispatched: 9977,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Sat Dec 01 2012 11:11:40 GMT+1000 (EST),
        parser: [Object],
        ondata: [Function],
        onend: [Function],
        _httpMessage: null,
        _paused: false },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Sat Dec 01 2012 11:11:42 GMT+1000 (EST),
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        app: [Object],
        _headers: [Object],
        _headerNames: [Object],
        req: [Circular],
        viewCallbacks: [],
        locals: [Object],
        end: [Function] },
     _paused: false,
     _peername: { address: '127.0.0.1', family: 'IPv4', port: 57235 } },
  httpVersion: '1.1',
  complete: true,
  headers: 
   { host: 'localhost:3005',
     connection: 'keep-alive',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
     referer: 'http://localhost:3005/',
     'accept-encoding': 'gzip,deflate,sdch',
     'accept-language': 'en-US,en;q=0.8',
     'accept-charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
     cookie: '262userid=wwv_user; connect.sid=s%3AzMGzw7wfrMsJdXD3mKWS6roz.UElKwn1jFvbV%2B6R2KOdbK%2FxcXdpnpQgVqZqxni2dfAU' },
  trailers: {},
  readable: false,
  _paused: false,
  _pendings: [],
  _endEmitted: true,
  url: '/adclick/8',
  method: 'GET',
  statusCode: null,
  client: 
   { domain: null,
     _events: 
      { drain: [Function: ondrain],
        timeout: [Object],
        error: [Function],
        close: [Object] },
     _maxListeners: 10,
     _handle: 
      { writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 62894,
     _bytesDispatched: 80531,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _connections: 6,
        connections: [Getter/Setter],
        allowHalfOpen: true,
        _handle: [Object],
        httpAllowHalfOpen: false,
        _connectionKey: '4:0.0.0.0:3005' },
     _idleTimeout: 120000,
     _idleNext: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 25218,
        _bytesDispatched: 9977,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Sat Dec 01 2012 11:11:40 GMT+1000 (EST),
        parser: [Object],
        ondata: [Function],
        onend: [Function],
        _httpMessage: null,
        _paused: false },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Sat Dec 01 2012 11:11:42 GMT+1000 (EST),
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        app: [Object],
        _headers: [Object],
        _headerNames: [Object],
        req: [Circular],
        viewCallbacks: [],
        locals: [Object],
        end: [Function] },
     _paused: false,
     _peername: { address: '127.0.0.1', family: 'IPv4', port: 57235 } },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  upgrade: false,
  originalUrl: '/adclick/8',
  _parsedUrl: 
   { pathname: '/adclick/8',
     path: '/adclick/8',
     href: '/adclick/8' },
  query: {},
  app: 
   { [Function: app]
     use: [Function],
     handle: [Function],
     listen: [Function],
     setMaxListeners: [Function],
     emit: [Function],
     addListener: [Function],
     on: [Function],
     once: [Function],
     removeListener: [Function],
     removeAllListeners: [Function],
     listeners: [Function],
     route: '/',
     stack: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     init: [Function],
     defaultConfiguration: [Function],
     engine: [Function],
     param: [Function],
     set: [Function],
     path: [Function],
     enabled: [Function],
     disabled: [Function],
     enable: [Function],
     disable: [Function],
     configure: [Function],
     get: [Function],
     post: [Function],
     put: [Function],
     head: [Function],
     delete: [Function],
     options: [Function],
     trace: [Function],
     copy: [Function],
     lock: [Function],
     mkcol: [Function],
     move: [Function],
     propfind: [Function],
     proppatch: [Function],
     unlock: [Function],
     report: [Function],
     mkactivity: [Function],
     checkout: [Function],
     merge: [Function],
     'm-search': [Function],
     notify: [Function],
     subscribe: [Function],
     unsubscribe: [Function],
     patch: [Function],
     all: [Function],
     del: [Function],
     render: [Function],
     request: {},
     response: {},
     cache: {},
     settings: 
      { 'x-powered-by': true,
        env: 'development',
        views: '/Users/menztrual/github/digital8/Property-Owl/views',
        'jsonp callback name': 'callback',
        'json spaces': 2,
        'view engine': 'jade' },
     engines: { '.jade': [Function] },
     viewCallbacks: [],
     _events: { mount: [Function] },
     _router: 
      { map: [Object],
        params: {},
        _params: [],
        caseSensitive: false,
        strict: false,
        middleware: [Function: router] },
     routes: 
      { get: [Object],
        post: [Object],
        put: [Object],
        head: [Object],
        delete: [Object],
        options: [Object],
        trace: [Object],
        copy: [Object],
        lock: [Object],
        mkcol: [Object],
        move: [Object],
        propfind: [Object],
        proppatch: [Object],
        unlock: [Object],
        report: [Object],
        mkactivity: [Object],
        checkout: [Object],
        merge: [Object],
        'm-search': [Object],
        notify: [Object],
        subscribe: [Object],
        unsubscribe: [Object],
        patch: [Object] },
     router: [Getter],
     locals: { [Function: locals] settings: [Object] },
     _usedRouter: true },
  res: 
   { domain: null,
     _events: { finish: [Function], header: [Function] },
     _maxListeners: 10,
     output: [],
     outputEncodings: [],
     writable: true,
     _last: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: true,
     _hasBody: true,
     _trailer: '',
     finished: false,
     socket: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 62894,
        _bytesDispatched: 80531,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: Sat Dec 01 2012 11:11:42 GMT+1000 (EST),
        parser: [Object],
        ondata: [Function],
        onend: [Function],
        _httpMessage: [Circular],
        _paused: false,
        _peername: [Object] },
     connection: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 62894,
        _bytesDispatched: 80531,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: Sat Dec 01 2012 11:11:42 GMT+1000 (EST),
        parser: [Object],
        ondata: [Function],
        onend: [Function],
        _httpMessage: [Circular],
        _paused: false,
        _peername: [Object] },
     app: 
      { [Function: app]
        use: [Function],
        handle: [Function],
        listen: [Function],
        setMaxListeners: [Function],
        emit: [Function],
        addListener: [Function],
        on: [Function],
        once: [Function],
        removeListener: [Function],
        removeAllListeners: [Function],
        listeners: [Function],
        route: '/',
        stack: [Object],
        init: [Function],
        defaultConfiguration: [Function],
        engine: [Function],
        param: [Function],
        set: [Function],
        path: [Function],
        enabled: [Function],
        disabled: [Function],
        enable: [Function],
        disable: [Function],
        configure: [Function],
        get: [Function],
        post: [Function],
        put: [Function],
        head: [Function],
        delete: [Function],
        options: [Function],
        trace: [Function],
        copy: [Function],
        lock: [Function],
        mkcol: [Function],
        move: [Function],
        propfind: [Function],
        proppatch: [Function],
        unlock: [Function],
        report: [Function],
        mkactivity: [Function],
        checkout: [Function],
        merge: [Function],
        'm-search': [Function],
        notify: [Function],
        subscribe: [Function],
        unsubscribe: [Function],
        patch: [Function],
        all: [Function],
        del: [Function],
        render: [Function],
        request: {},
        response: {},
        cache: {},
        settings: [Object],
        engines: [Object],
        viewCallbacks: [],
        _events: [Object],
        _router: [Object],
        routes: [Object],
        router: [Getter],
        locals: [Object],
        _usedRouter: true },
     _headers: { 'x-powered-by': 'Express' },
     _headerNames: { 'x-powered-by': 'X-Powered-By' },
     req: [Circular],
     viewCallbacks: [],
     locals: 
      { [Function: locals]
        flash: [],
        session: [Object],
        globals: [Object],
        modules: [Object],
        objUser: [Object],
        menu: {},
        navigation: [Object],
        ad: [Object] },
     end: [Function] },
  next: [Function: next],
  _startTime: Sat Dec 01 2012 11:11:42 GMT+1000 (EST),
  body: {},
  files: {},
  originalMethod: 'GET',
  updateParam: [Function],
  check: [Function],
  checkHeader: [Function],
  onValidationError: [Function],
  validationErrors: [Function],
  filter: [Function],
  sanitize: [Function],
  assert: [Function],
  validate: [Function],
  secret: 'secretsecret',
  cookies: { '262userid': 'wwv_user' },
  signedCookies: { 'connect.sid': 'zMGzw7wfrMsJdXD3mKWS6roz' },
  sessionStore: 
   { sessions: { zMGzw7wfrMsJdXD3mKWS6roz: '{cookie:{originalMaxAge:null,expires:null,httpOnly:true,path:/},user_id:1}' },
     generate: [Function],
     _events: { disconnect: [Function], connect: [Function] } },
  sessionID: 'zMGzw7wfrMsJdXD3mKWS6roz',
  session: 
   { cookie: 
      { path: '/',
        _expires: null,
        originalMaxAge: null,
        httpOnly: true },
     user_id: 1 },
  flash: [Function],
  _route_index: 4,
  route: 
   { path: '/adclick/:id',
     method: 'get',
     callbacks: [ [Function] ],
     keys: [ [Object] ],
     regexp: /^\/adclick\/(?:([^\/]+?))\/?$/i,
     params: [ id: '8' ] },
  params: [ id: '8' ] }
