exports.index   = (require '../behaviors/index')   Category, plural: 'categories'
exports.add     = (require '../behaviors/add')     Category, plural: 'categories'
exports.create  = (require '../behaviors/create')  Category, plural: 'categories'
exports.edit    = (require '../behaviors/edit')    Category, plural: 'categories'
exports.update  = (require '../behaviors/update')  Category, plural: 'categories'
exports.delete  = (require '../behaviors/delete')  Category, plural: 'categories'
exports.destroy = (require '../behaviors/destroy') Category, plural: 'categories'